--- #YAML:1.0
name:               Apache2-Authen-Passphrase
version:            0.001001
abstract:           basic authentication with Authen::Passphrase
author:
    - Marius Gavrilescu <marius@ieval.ro>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache2::Access:      0
    Apache2::Const:       0
    Apache2::RequestRec:  0
    Authen::Passphrase:   0
    Authen::Passphrase::BlowfishCrypt:  0
    perl:                 5.014000
    YAML::Any:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
